# Generated by Django 3.2.15 on 2022-09-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_province', models.CharField(db_column='民居省份', max_length=50, verbose_name='民居省份')),
                ('resident_number', models.CharField(db_column='民居编号', max_length=100, verbose_name='民居编号')),
                ('resident_type', models.TextField(db_column='民居类型名称', verbose_name='民居类型名称')),
                ('resident_overview', models.TextField(db_column='民居概述', verbose_name='民居概述')),
                ('distribution', models.TextField(db_column='分布', verbose_name='分布')),
                ('structure', models.TextField(db_column='形制', verbose_name='形制')),
                ('construct', models.TextField(db_column='建造', verbose_name='建造')),
                ('represent_building', models.TextField(db_column='代表建筑', verbose_name='代表建筑')),
                ('factor', models.TextField(db_column='成因', verbose_name='成因')),
                ('comparison_evolution', models.TextField(db_column='比较与演变', verbose_name='比较与演变')),
                ('attached_picture', models.TextField(db_column='附图', verbose_name='附图')),
            ],
            options={
                'verbose_name': '民居信息',
                'verbose_name_plural': '民居信息',
                'db_table': '民居表',
            },
        ),
    ]
